copperegg:
  apikey: "YOUR_APIKEY"
aws:
  access_key_id: "YourAWSAccessKey"
  secret_access_key: "SuperSecretAWSKeyGoesHere"
  services:
    - elb
    - rds
    - ec2
    - billing
elb:
  group_name: "AWSelb"
  group_label: "ELB Metrics"
  dashboard: "AWS ELB"

rds:
  group_name: "AWSrds"
  group_label: "RDS Metrics"
  dashboard: "AWS RDS"

ec2:
  group_name: "AWSec2"
  group_label: "EC2 Metrics"
  dashboard: "AWS EC2"

billing:
  group_name: "AWSbilling"
  group_label: "AWS Billing"
  dashboard: "AWS Billing"
