copperegg:
  apikey:  'YOUR_API_KEY_HERE'
  frequency: 60
  services:
  - remote_server

remote_server:
  group_name: "remote_server"
  group_label: "Remote Server"
  dashboard: "Remote Monitoring Dashboard"
  servers:
  - name: 'my_server1'
    host: 'subdomain.domain.com'
    user: 'user'
    password: ''
    port: 22
    key: '/home/user/.ssh/id_rsa'
