copperegg:
  apikey: "-------------"
  apihost: "http://api.cuegglocal.com"
  frequency: 60
  services:
  - cassandra
cassandra:
  group_name: "Cassandra_Metrics"
  group_label: "Cassandra Metrics"
  dashboard: "Cassandra_Clusters"
  clusters:
  -
    name: "cassandra-cluster-01"
    hostname: 'localhost'
    port: '7199'
    username:
    password:
