copperegg:
  apikey:  'YOUR_APIKEY'
  frequency: 60
  services:
  - postgresql

postgresql:
  group_name: "pg_metrics"
  group_label: "PostgreSQl Metrics"
  dashboard: "PostgreSQL"
  servers:
  - name: "postgre-server1"
    hostname: 'localhost'
    port: 5432
    sslmode: 'disable'
    databases:
    - name: "test"
      username: 'YOUR USERNAME'
      password: 'YOUR PASSWORD'

